### ISSUE TITLE
Navigation issues when directly accessing a section in the wiki

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/wiki#151]
Hi, I'm having navigation issues when I directly go into a section of the wiki. So far, I'm seeing that it happens when accessing the [mirrors section](https://wiki.almalinux.org/Mirrors.html), but I didn't check whether it happens with other sections.

Steps to reproduce:

# Open a new tab and go into https://wiki.almalinux.org/Mirrors.html
# Try to move to another section of the wiki using the navigation menu

Expected result:

The browser takes me to the section of the wiki I clicked on the menu

Actual result:

Although the address bar gets updated, I remain in the mirrors section

In Chrome's dev/inspect panel I can see the following error in the console:

```
app.2f3c144b.js:12 DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:47748)
    at d (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:60503)
    at u (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:60240)
    at h (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:60589)
    at C (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:63927)
    at C (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:63862)
    at C (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:63862)
    at C (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:63862)
    at C (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:63862)
    at C (https://wiki.almalinux.org/assets/js/app.2f3c144b.js:12:63862)
```

I guess that there's something inside the mirror section that bothers Vuepress, see the following [related issue](https://github.com/vuejs/vuepress/issues/1692)

**Comment by sakelestemur** [comment]
Hello Javier,
Thank you for sharing the issue and possible reasons. We are now working on it.

**Comment by javihernandez** [comment]
Thanks @sakelestemur!
BTW, yesterday night I build and ran the wiki locally, and to my surprise, I couldn't reproduce the problem :shrug: 
Good luck with the bug hunt ;)

**Comment by sakelestemur** [comment]
You're welcome @javihernandez. 
And I also could not reproduce it on my local machine. The navigation works on the mirror page without any problem.
So, it seems we should make the bug hunt deeper. :) Thanks again!

**Comment by sakelestemur** [comment]
Hello again @javihernandez 
It may be a web server misconfiguration. But also I checked the error on the browser development tools that you've mentioned. If everything is okay, it should be because of JS minifying. We should check CloudFlare settings.

**Comment by bennyvasquez** [comment]
@javihernandez I'm not seeing this today when testing either. Can you confirm if you're still seeing this problem?

**Comment by javihernandez** [comment]
Hey @bennyvasquez, yes, the issue is still present
