### ISSUE TITLE
Problem with building the wiki

### ISSUE THREAD

**Issue by sandorex** [AlmaLinux/wiki#272]
I cannot build the wiki

```
% yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @vue/babel-plugin-jsx@npm:1.1.1 doesn't provide @babel/core (pacf39), requested by @babel/plugin-syntax-jsx
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yallist@npm:3.1.1 can't be found in the cache and will be fetched f
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched f
➤ YN0013: │ yargs-parser@npm:13.1.2 can't be found in the cache and will be fet
➤ YN0013: │ yargs@npm:13.3.2 can't be found in the cache and will be fetched fr
➤ YN0013: │ zepto@npm:1.2.0 can't be found in the cache and will be fetched fro
➤ YN0000: └ Completed in 0s 861ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ highlight.js@npm:9.18.5 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.30.2 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.14.7 must be built because it never has been before or the last one failed
➤ YN0007: │ vuepress@npm:1.9.9 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 384ms
➤ YN0000: Done with warnings in 2s 640ms

% yarn docs:dev
/var/home/sandorex/slowmf/ws/almalinux-wiki/.pnp.cjs:23888
      Error.captureStackTrace(firstError);
            ^

Error: vuepress tried to access @vuepress/shared-utils, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @vuepress/shared-utils
Required by: vuepress@npm:1.9.9 (via /var/home/sandorex/slowmf/ws/almalinux-wiki/.yarn/unplugged/vuepress-npm-1.9.9-61cbd83bbc/node_modules/vuepress/lib/)

Require stack:
- /var/home/sandorex/slowmf/ws/almalinux-wiki/.yarn/unplugged/vuepress-npm-1.9.9-61cbd83bbc/node_modules/vuepress/lib/checkEnv.js
- /var/home/sandorex/slowmf/ws/almalinux-wiki/.yarn/unplugged/vuepress-npm-1.9.9-61cbd83bbc/node_modules/vuepress/cli.js
    at require$$0.Module._resolveFilename (/var/home/sandorex/slowmf/ws/almalinux-wiki/.pnp.cjs:23888:13)
    at require$$0.Module._load (/var/home/sandorex/slowmf/ws/almalinux-wiki/.pnp.cjs:23738:42)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/var/home/sandorex/slowmf/ws/almalinux-wiki/.yarn/unplugged/vuepress-npm-1.9.9-61cbd83bbc/node_modules/vuepress/lib/checkEnv.js:7:27)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at require$$0.Module._extensions..js (/var/home/sandorex/slowmf/ws/almalinux-wiki/.pnp.cjs:23932:33)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at require$$0.Module._load (/var/home/sandorex/slowmf/ws/almalinux-wiki/.pnp.cjs:23769:14)

Node.js v18.16.0

% node --version
v18.16.0
% npm --version
9.5.1
% yarn --version
3.6.0
```

I've also tried latest node js and same issue

**Comment by sandorex** [comment]
Tried adding adding every package it said is not declared
```diff
% git diff package.json                                                  [ 1 ]
diff --git a/package.json b/package.json
index acb95c1..0fca417 100644
--- a/package.json
+++ b/package.json
@@ -7,6 +7,9 @@
     "docs:build": "vuepress build docs"
   },
   "devDependencies": {
+    "@vuepress/shared-utils": "^1.9.9",
+    "lru-cache": "^9.1.2",
+    "markdown-it-emoji": "^2.0.2",
     "vuepress": "^1.8.2"
   }
 }
```

And now getting
```
/var/home/sandorex/slowmf/ws/almalinux-wiki/.yarn/cache/@vuepress-shared-utils-npm-1.9.9-44b4d41523-8fc6e9d7d4.zip/node_modules/@vuepress/shared-utils/lib/extractHeaders.js:15
const cache = new lru_cache_1.default({ max: 1000 });
              ^

TypeError: lru_cache_1.default is not a constructor
    at Object.<anonymous> (/var/home/sandorex/slowmf/ws/almalinux-wiki/.yarn/cache/@vuepress-shared-utils-npm-1.9.9-44b4d41523-8fc6e9d7d4.zip/node_modules/@vuepress/shared-utils/lib/extractHeaders.js:15:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at require$$0.Module._extensions..js (/var/home/sandorex/slowmf/ws/almalinux-wiki/.pnp.cjs:23952:33)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at require$$0.Module._load (/var/home/sandorex/slowmf/ws/almalinux-wiki/.pnp.cjs:23789:14)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/var/home/sandorex/slowmf/ws/almalinux-wiki/.yarn/cache/@vuepress-shared-utils-npm-1.9.9-44b4d41523-8fc6e9d7d4.zip/node_modules/@vuepress/shared-utils/lib/index.js:40:42)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.16.0
```

**Comment by andrewlukoshko** [comment]
Fixed by https://github.com/AlmaLinux/wiki/pull/359
